# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.registration:
        class: AKYOS\EasyCoproBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    artisan:
        class: AKYOS\EasyCoproBundle\Form\Artisan
        tags:
            -  { name: form.type }